### ISSUE TITLE
Umbrella Issue: First Open Source Launch Targets

### ISSUE THREAD

**Issue by quinton-hoole** [amino-os/Amino.Run#654]
This is the root of the tree of all issues to track all outstanding items for open sourcing.

The structure is as follows:

1. This issue (the root) identifies all of the highest level requirements, with linked issues (main branches of the tree) to track the detail under each one of those.
2. For each of the linked issues (the main branches of the tree), a more detailed description of the requirements, current status, and links to all the detailed issues and PR's that need to be resolved to fulfill that requirement (at least in terms of MVP for open sourcing).

See also: https://help.github.com/en/articles/about-task-lists

Requirements: 

- [x] open this issue and check that completion tracking works correctly.
- [ ] **Introductory documentation** should be easily accessible, easy to understand and accurate. #655
- [ ] **Getting Started Experience** for developers wanting to try it out (i.e. download, build, deploy, run a compelling example) should be excellent. #656
- [ ] **Example Tutorials** and example applications should be well coded, well commented and create a very positive impression. #657
- [ ] **Multi-language** support - integration tests and example tutorials should cover at least 3 sufficiently different languages well (e.g. Java, Ruby, Python, and ideally an LLVM language like Rust or C++), as well as any other related languages.(JavaScript, Kotlin etc).  At least some of the examples should cover client and server written in different languages, and passing user defined types between them. #658
- [ ] **The most important DMs** should work well, and be covered by integration tests and examples/tutorials.  Most important DM's are approximately (1) Consensus (2) DHT/Sharding (3) AtLeastOnceRPC (4) DurableSerializableRPC (5) ExplicitMigration (6) AutomaticMigration (7) OptimisticConcurrentTransaction (8) 2PhaseCommit distributed transactions. #659 .  NOTE: Some of the combinations of these DMs must be handled. However that is marked below separately and handled in a separate issue. However, ensure it! That is the key value. (see multi-DM below)
- [ ] **Microservice Monitoring and Metrics** - note that many of the above imply/require working microservice monitoring and metrics #643 (Currently the basic monitoring framework. Later optimise)
- [ ] **Multi-DM** - combining multiple important DMS' (see above) in useful combinations should work well and be covered by integration tests and examples/tutorials. #660
- [ ] **Things that don't work** well should be explicitly called out and documented.  For example broken DM's, specific combinations of DM's that are known not to work, specific combinations of languages that are known not to work, etc. #661
