### ISSUE TITLE
Umbrella issue: Multi-language support - check and polish it for open source release

### ISSUE THREAD

**Issue by quinton-hoole** [amino-os/Amino.Run#658]
Multi-language support - integration tests and example tutorials should cover at least 3 sufficiently different languages well (e.g. Java, Ruby, Python, and ideally an LLVM language like Rust or C++), as well as any other related languages.(JavaScript, Kotlin etc). At least some of the examples should cover client and server written in different languages, and passing user defined types between them.

See #654.

Detail to be filled in here. Individual issues and PR's to be linked to this issue.

Check list: (please add/remove as required, and check off once complete):

Same language for client and server:

- [x] Java
- [x] Ruby
- [ ] Python
- [x] JavaScript
- [ ] Rust
- [ ] C++
- [ ] Kotlin

Examples of different languages for client and server (please add/remove as required, and check once verified):

- [x] Java Client with Ruby Server
- [x] Java Client with JS Server
- [ ] Java Client with Python Server
- [ ] Ruby Client with Java Server
- [ ] ...
