### ISSUE TITLE
Umbrella Issue: Things that don't work well should be explicitly called out and documented.

### ISSUE THREAD

**Issue by quinton-hoole** [amino-os/Amino.Run#661]
Things that don't work well should be explicitly called out and documented.  For example:

(please add items as necessary, and check them off once complete).

- [ ] broken DM's, 
- [ ] specific combinations of DM's that are known not to work, 
- [ ] specific combinations of languages that are known not to work
- [ ] other broken stuff

See #654.

Detail to be filled in here. Individual issues and PR's to be linked to this issue.
