### ISSUE TITLE
[MultiDM-Umbrella] Investigate/fix combinations that do not work as expected.

### ISSUE THREAD

**Issue by sungwook-moon** [amino-os/Amino.Run#744]
Google Sheet for the DM combination matrix:
https://docs.google.com/spreadsheets/d/1O2flMIe2BWo8x6N87WInqNyvGamk-F4VtV8BngATIRE/edit#gid=0

*: higher priority which has a greater impact.

Investigate the integration test failure for followings:
- [ ] LBFrontEnd fails for all combinations (#752)
- [ ] LBMasterSlave fails a few as an outer DM (#754)
- [ ] Consensus fails a few as an outer DM (#755)
- [ ] OptimisticConcurrency fails a few as an outer DM (#756)
- [ ] TwoPCCooridator fails a few as an outer DM (#757)

Investigate each issue which passes the integration tests but fails to show the desired result.
- [ ] CacheLeaseDM accesses cached object in client only (1 & 2 in the matrix) (#758)
- [ ] CacheLease + Consensus fails when there are multiple servers (5 in the matrix) (#759)
- [ ] DHT DM is as an outer DM does not distribute the partition to other servers (3 in the matrix) (#760)
- [ ] LBMasterSlave DM as an outer DM does not distribute the replicas to other servers (3 in the matrix) (#761)
- [ ] LBMasterSlave + LBMasterSlave fails at one or more of the servers (4 in the matrix) (#762)
- [ ] TwoPCCooridator DM + LBMasterSlave fails when there are multiple servers (5 in the matrix) (#763)
- [ ] Consensus DM as an outer DM does not distribute the replicas to other servers (3 in the matrix) (#764)
- [ ] Consensus + CacheLease fails due to cache lease failure (6 in the matrix) (#765)

Please create an issue when starting to investigate each issue and reference this issue. Mark each when completed.
